### ISSUE TITLE
queryComponentMetadataComponentId.json using wrong filter?

### ISSUE THREAD

**Issue by requiem1991** [OfficialBoomi/boomicicd-cli#3]
Not quite sure about this but the file queryComponentMetadataComponentId.json is using a name filter instead of componentid filter resulting in no records returned when trying to query on componentId.

![image](https://user-images.githubusercontent.com/67415804/85698992-724d8f00-b6db-11ea-9178-3744468b7758.png)

Changing it to componentId solved the issue for me.

Michael van Eck
Datacon B.V.

**Comment by boomiguy** [comment]
Thanks for the feedback.
